Jules
Sidekick-EIP/app-mobile-V2 pull request #5
Opened 2023-10-13 00:14 UTC by Jules-gitclerc

2023-10-14 12:36 UTC, Yzorek commented on lib/main.dart
> +  final TokenStorage tokenStorage = TokenStorage();
Je sais pas pourquoi t'as ces modifs là c'est ma branche ça, tu as du partir de ma branche

2023-10-14 12:37 UTC, Yzorek commented on lib/view/nutrition/home_nutrition_view.dart
??

2023-10-14 12:38 UTC, Yzorek commented on lib/view/nutrition/nutrition_view.dart
Pourquoi avoir changé le nom, il était très bien

2023-10-14 12:49 UTC, Yzorek commented
Il y a qq trucs que je comprend pas dans le profil
Dans objectifs y'a les infos du compte ?
Dans mon sidekick y'a une création d'exo ?
Et la nutrition fonctionne pas

2023-10-14 13:05 UTC, Jules-gitclerc commented on lib/main.dart
> +  final TokenStorage tokenStorage = TokenStorage();
Pour éviter d’avoir à me log pour reload l’app, c’est les même modifs que sur ta branche mais vu que c’était pas sur main

2023-10-14 13:06 UTC, Jules-gitclerc commented on lib/view/nutrition/nutrition_view.dart
parce que ça veut rien dire le home_ vu c’est déjà une view si il d’autre page qui ne sont pas sur cette view il faudra indiquer avec _screen

2023-10-14 13:08 UTC, Jules-gitclerc commented
La modification d’objectif n’est pas finaliser c’est la page compte en attendant, la nutrition ne fonctionnait pas de base à revoir au niveau des requêtes, avec les modification d’optimisation du code + modif du calendrier

2023-10-14 13:16 UTC, Yzorek commented on lib/view/nutrition/nutrition_view.dart
Ok pourquoi pas

2023-10-16 17:48 UTC, Yzorek requested changes

2023-10-16 17:48 UTC, Yzorek commented on lib/view/home/home_view.dart
> +
Requête déja faite dans le controller

2023-10-16 20:26 UTC, Yzorek approved these changes

2023-10-16 21:23 UTC, merged